pwa:
  manifest:
    enabled: true
    name: "AppliPAPs"
    short_name: "AppliPAPs"
    start_url: "/"
    id: "/"
    display: "standalone"
    background_color: "#ffffff"
    theme_color: "#4285f4"
    icons:
      - src: "images/png/papsimmo-512x512.png"
        sizes: [512]
  serviceworker:
    enabled: true
    src: "sw.js"
    workbox:
      cache_manifest: true
      clear_cache: true
